[package]
name = "beeline"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
config = { version = "0.13.3" }
crossterm = { version = "0.27" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
structopt = "^0.3"
chrono = "^0.4"
colored = "^2.0"