name: Monitor beeminder-rs updates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Get current commit
        id: current
        run: |
          CURRENT_COMMIT=$(git ls-remote https://github.com/felixmde/beeminder-rs.git main | cut -f1)
          echo "commit=$CURRENT_COMMIT" >> $GITHUB_OUTPUT
      
      - name: Check Cargo.lock
        id: check_lock
        run: |
          CURRENT_HASH=$(grep -A 4 'name = "beeminder-rs"' Cargo.lock | grep -o '#[a-f0-9]\+' | cut -c 2-)
          if [ "$CURRENT_HASH" != "${{ steps.current.outputs.commit }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_lock.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update beeminder-rs dependency"
          title: "Update beeminder-rs dependency"
          body: |
            beeminder-rs has been updated:
            Current: ${{ steps.current.outputs.commit }}
            Previous: $(grep -A 4 'name = "beeminder-rs"' Cargo.lock | grep -o '#[a-f0-9]\+' | cut -c 2-)
          branch: update-beeminder-rs
          delete-branch: true
